//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     STEM-107
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using STEM107;

namespace STEM107.Diagnostics.DiagItemsList
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IDiagItemsListByItem
    {

        /// <summary>
        /// Diag-Items-List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Helper Diag-Items-List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Enable(ushort listItemIndex, DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Helper Diag-Items-List.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Enable(ushort listItemIndex, bool digital);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class DiagItemsList
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item1_EnableState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, bool digital)
        {
            List_Item_Enable(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }


        #endregion
    }

    /// <summary>
    /// DiagItemsList
    /// </summary>
    public partial interface IDiagItemsList : IDiagItemsListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Diag-Items-List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item1_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item1_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item2_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item2_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item3_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item3_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item4_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item4_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item5_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item5_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item6_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item6_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item7_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item7_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item7_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item7_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item8_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item8_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item8_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item8_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item9_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item9_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item9_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item9_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item10_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item10_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item10_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item10_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item11_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item11_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item11_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item11_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item12_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item12_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item12_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item12_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item13_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item13_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item13_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item13_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item14_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item14_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item14_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item14_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item15_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item15_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item15_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item15_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item16_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item16_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item16_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item16_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item17_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item17_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item17_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item17_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item18_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item18_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item18_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item18_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item19_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item19_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item19_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item19_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item20_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item20_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item20_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item20_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item21_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item21_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item21_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item21_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item22_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item22_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item22_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item22_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item23_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item23_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item23_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item23_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item24_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item24_Visible(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item24_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item24_Visible(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item1_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item1_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item2_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item2_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item3_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item3_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item4_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item4_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item5_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item5_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item5_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item5_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item6_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item6_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item6_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item6_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item7_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item7_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item7_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item7_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item8_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item8_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item8_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item8_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item9_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item9_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item9_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item9_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item10_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item10_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item10_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item10_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item11_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item11_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item11_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item11_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item12_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item12_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item12_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item12_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item13_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item13_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item13_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item13_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item14_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item14_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item14_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item14_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item15_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item15_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item15_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item15_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item16_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item16_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item16_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item16_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item17_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item17_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item17_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item17_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item18_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item18_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item18_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item18_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item19_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item19_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item19_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item19_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item20_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item20_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item20_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item20_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item21_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item21_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item21_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item21_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item22_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item22_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item22_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item22_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item23_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item23_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item23_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item23_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List_Item24_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagItemsList_List_Item24_Enable(DiagItemsListBoolInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List_Item24_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagItemsList_List_Item24_Enable(bool digital);

        /// <summary>
        /// Diag-Items-List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void DiagItemsList_Set_Number_Of_Items(DiagItemsListUShortInputSigDelegate callback);

        /// <summary>
        /// Diag-Items-List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void DiagItemsList_Set_Number_Of_Items(ushort analog);

        /// <summary>
        /// Diag-Items-List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void DiagItemsList_Set_Number_Of_Items(short analog);

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[0]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[1]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[2]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[3]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[4]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_4_ Items_4_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[5]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_5_ Items_5_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[6]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_6_ Items_6_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[7]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_7_ Items_7_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[8]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_8_ Items_8_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[9]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_9_ Items_9_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[10]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_10_ Items_10_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[11]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_11_ Items_11_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[12]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_12_ Items_12_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[13]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_13_ Items_13_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[14]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_14_ Items_14_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[15]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_15_ Items_15_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[16]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_16_ Items_16_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[17]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_17_ Items_17_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[18]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_18_ Items_18_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[19]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_19_ Items_19_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[20]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_20_ Items_20_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[21]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_21_ Items_21_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[22]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_22_ Items_22_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]s[23]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItems_23_ Items_23_ { get; }

        /// <summary>
        /// ComplexComponent Diag-Item.Items[{0}]
        /// </summary>
        STEM107.Diagnostics.DiagItemsList.IItem Item { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="diagitemslist">The <see cref="IDiagItemsList"/> on which to apply the feedback.</param>
    public delegate void DiagItemsListBoolInputSigDelegate(BoolInputSig boolInputSig, IDiagItemsList diagitemslist);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="diagitemslist">The <see cref="IDiagItemsList"/> on which to apply the feedback.</param>
    public delegate void DiagItemsListUShortInputSigDelegate(UShortInputSig uShortInputSig, IDiagItemsList diagitemslist);

    /// <summary>
    /// DiagItemsList
    /// </summary>
    internal partial class DiagItemsList : IDiagItemsList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item1_Visible
                /// Diag-Items-List.List_Item1_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item1_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item2_Visible
                /// Diag-Items-List.List_Item2_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item2_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item3_Visible
                /// Diag-Items-List.List_Item3_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item3_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item4_Visible
                /// Diag-Items-List.List_Item4_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item4_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item5_Visible
                /// Diag-Items-List.List_Item5_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item5_VisibleState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item6_Visible
                /// Diag-Items-List.List_Item6_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item6_VisibleState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item7_Visible
                /// Diag-Items-List.List_Item7_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item7_VisibleState = 7;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item8_Visible
                /// Diag-Items-List.List_Item8_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item8_VisibleState = 8;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item9_Visible
                /// Diag-Items-List.List_Item9_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item9_VisibleState = 9;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item10_Visible
                /// Diag-Items-List.List_Item10_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item10_VisibleState = 10;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item11_Visible
                /// Diag-Items-List.List_Item11_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item11_VisibleState = 11;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item12_Visible
                /// Diag-Items-List.List_Item12_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item12_VisibleState = 12;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item13_Visible
                /// Diag-Items-List.List_Item13_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item13_VisibleState = 13;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item14_Visible
                /// Diag-Items-List.List_Item14_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item14_VisibleState = 14;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item15_Visible
                /// Diag-Items-List.List_Item15_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item15_VisibleState = 15;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item16_Visible
                /// Diag-Items-List.List_Item16_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item16_VisibleState = 16;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item17_Visible
                /// Diag-Items-List.List_Item17_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item17_VisibleState = 17;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item18_Visible
                /// Diag-Items-List.List_Item18_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item18_VisibleState = 18;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item19_Visible
                /// Diag-Items-List.List_Item19_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item19_VisibleState = 19;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item20_Visible
                /// Diag-Items-List.List_Item20_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item20_VisibleState = 20;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item21_Visible
                /// Diag-Items-List.List_Item21_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item21_VisibleState = 21;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item22_Visible
                /// Diag-Items-List.List_Item22_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item22_VisibleState = 22;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item23_Visible
                /// Diag-Items-List.List_Item23_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item23_VisibleState = 23;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item24_Visible
                /// Diag-Items-List.List_Item24_Visible
                /// </summary>
                public const uint DiagItemsList_List_Item24_VisibleState = 24;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item1_Enable
                /// Diag-Items-List.List_Item1_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item1_EnableState = 25;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item2_Enable
                /// Diag-Items-List.List_Item2_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item2_EnableState = 26;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item3_Enable
                /// Diag-Items-List.List_Item3_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item3_EnableState = 27;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item4_Enable
                /// Diag-Items-List.List_Item4_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item4_EnableState = 28;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item5_Enable
                /// Diag-Items-List.List_Item5_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item5_EnableState = 29;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item6_Enable
                /// Diag-Items-List.List_Item6_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item6_EnableState = 30;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item7_Enable
                /// Diag-Items-List.List_Item7_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item7_EnableState = 31;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item8_Enable
                /// Diag-Items-List.List_Item8_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item8_EnableState = 32;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item9_Enable
                /// Diag-Items-List.List_Item9_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item9_EnableState = 33;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item10_Enable
                /// Diag-Items-List.List_Item10_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item10_EnableState = 34;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item11_Enable
                /// Diag-Items-List.List_Item11_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item11_EnableState = 35;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item12_Enable
                /// Diag-Items-List.List_Item12_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item12_EnableState = 36;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item13_Enable
                /// Diag-Items-List.List_Item13_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item13_EnableState = 37;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item14_Enable
                /// Diag-Items-List.List_Item14_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item14_EnableState = 38;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item15_Enable
                /// Diag-Items-List.List_Item15_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item15_EnableState = 39;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item16_Enable
                /// Diag-Items-List.List_Item16_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item16_EnableState = 40;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item17_Enable
                /// Diag-Items-List.List_Item17_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item17_EnableState = 41;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item18_Enable
                /// Diag-Items-List.List_Item18_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item18_EnableState = 42;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item19_Enable
                /// Diag-Items-List.List_Item19_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item19_EnableState = 43;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item20_Enable
                /// Diag-Items-List.List_Item20_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item20_EnableState = 44;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item21_Enable
                /// Diag-Items-List.List_Item21_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item21_EnableState = 45;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item22_Enable
                /// Diag-Items-List.List_Item22_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item22_EnableState = 46;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item23_Enable
                /// Diag-Items-List.List_Item23_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item23_EnableState = 47;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.List_Item24_Enable
                /// Diag-Items-List.List_Item24_Enable
                /// </summary>
                public const uint DiagItemsList_List_Item24_EnableState = 48;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: Diagnostics.DiagItemsList.Set_Number_Of_Items
                /// Diag-Items-List.List Number Of Items
                /// </summary>
                public const uint DiagItemsList_Set_Number_Of_ItemsState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagItemsList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal DiagItemsList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagItemsList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal DiagItemsList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagItemsList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            Items_0_ = new STEM107.Diagnostics.DiagItemsList.Items_0_(ComponentMediator, 15, 24);
            Items_1_ = new STEM107.Diagnostics.DiagItemsList.Items_1_(ComponentMediator, 16, 24);
            Items_2_ = new STEM107.Diagnostics.DiagItemsList.Items_2_(ComponentMediator, 17, 24);
            Items_3_ = new STEM107.Diagnostics.DiagItemsList.Items_3_(ComponentMediator, 18, 24);
            Items_4_ = new STEM107.Diagnostics.DiagItemsList.Items_4_(ComponentMediator, 19, 24);
            Items_5_ = new STEM107.Diagnostics.DiagItemsList.Items_5_(ComponentMediator, 20, 24);
            Items_6_ = new STEM107.Diagnostics.DiagItemsList.Items_6_(ComponentMediator, 21, 24);
            Items_7_ = new STEM107.Diagnostics.DiagItemsList.Items_7_(ComponentMediator, 22, 24);
            Items_8_ = new STEM107.Diagnostics.DiagItemsList.Items_8_(ComponentMediator, 23, 24);
            Items_9_ = new STEM107.Diagnostics.DiagItemsList.Items_9_(ComponentMediator, 24, 24);
            Items_10_ = new STEM107.Diagnostics.DiagItemsList.Items_10_(ComponentMediator, 25, 24);
            Items_11_ = new STEM107.Diagnostics.DiagItemsList.Items_11_(ComponentMediator, 26, 24);
            Items_12_ = new STEM107.Diagnostics.DiagItemsList.Items_12_(ComponentMediator, 27, 24);
            Items_13_ = new STEM107.Diagnostics.DiagItemsList.Items_13_(ComponentMediator, 28, 24);
            Items_14_ = new STEM107.Diagnostics.DiagItemsList.Items_14_(ComponentMediator, 29, 24);
            Items_15_ = new STEM107.Diagnostics.DiagItemsList.Items_15_(ComponentMediator, 30, 24);
            Items_16_ = new STEM107.Diagnostics.DiagItemsList.Items_16_(ComponentMediator, 31, 24);
            Items_17_ = new STEM107.Diagnostics.DiagItemsList.Items_17_(ComponentMediator, 32, 24);
            Items_18_ = new STEM107.Diagnostics.DiagItemsList.Items_18_(ComponentMediator, 33, 24);
            Items_19_ = new STEM107.Diagnostics.DiagItemsList.Items_19_(ComponentMediator, 34, 24);
            Items_20_ = new STEM107.Diagnostics.DiagItemsList.Items_20_(ComponentMediator, 35, 24);
            Items_21_ = new STEM107.Diagnostics.DiagItemsList.Items_21_(ComponentMediator, 36, 24);
            Items_22_ = new STEM107.Diagnostics.DiagItemsList.Items_22_(ComponentMediator, 37, 24);
            Items_23_ = new STEM107.Diagnostics.DiagItemsList.Items_23_(ComponentMediator, 38, 24);
            Item = new STEM107.Diagnostics.DiagItemsList.Item(ComponentMediator, 15, 24);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((STEM107.Diagnostics.DiagItemsList.Items_0_)Items_0_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_1_)Items_1_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_2_)Items_2_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_3_)Items_3_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_4_)Items_4_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_5_)Items_5_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_6_)Items_6_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_7_)Items_7_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_8_)Items_8_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_9_)Items_9_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_10_)Items_10_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_11_)Items_11_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_12_)Items_12_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_13_)Items_13_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_14_)Items_14_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_15_)Items_15_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_16_)Items_16_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_17_)Items_17_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_18_)Items_18_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_19_)Items_19_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_20_)Items_20_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_21_)Items_21_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_22_)Items_22_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_23_)Items_23_).AddDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((STEM107.Diagnostics.DiagItemsList.Items_0_)Items_0_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_1_)Items_1_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_2_)Items_2_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_3_)Items_3_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_4_)Items_4_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_5_)Items_5_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_6_)Items_6_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_7_)Items_7_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_8_)Items_8_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_9_)Items_9_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_10_)Items_10_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_11_)Items_11_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_12_)Items_12_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_13_)Items_13_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_14_)Items_14_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_15_)Items_15_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_16_)Items_16_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_17_)Items_17_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_18_)Items_18_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_19_)Items_19_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_20_)Items_20_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_21_)Items_21_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_22_)Items_22_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Items_23_)Items_23_).RemoveDevice(device);

            ((STEM107.Diagnostics.DiagItemsList.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void DiagItemsList_List_Item1_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item1_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item1_Enable(bool digital)
        {
            DiagItemsList_List_Item1_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item1_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item1_Visible(bool digital)
        {
            DiagItemsList_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item10_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item10_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item10_Enable(bool digital)
        {
            DiagItemsList_List_Item10_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item10_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item10_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item10_Visible(bool digital)
        {
            DiagItemsList_List_Item10_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item11_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item11_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item11_Enable(bool digital)
        {
            DiagItemsList_List_Item11_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item11_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item11_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item11_Visible(bool digital)
        {
            DiagItemsList_List_Item11_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item12_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item12_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item12_Enable(bool digital)
        {
            DiagItemsList_List_Item12_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item12_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item12_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item12_Visible(bool digital)
        {
            DiagItemsList_List_Item12_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item13_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item13_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item13_Enable(bool digital)
        {
            DiagItemsList_List_Item13_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item13_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item13_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item13_Visible(bool digital)
        {
            DiagItemsList_List_Item13_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item14_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item14_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item14_Enable(bool digital)
        {
            DiagItemsList_List_Item14_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item14_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item14_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item14_Visible(bool digital)
        {
            DiagItemsList_List_Item14_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item15_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item15_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item15_Enable(bool digital)
        {
            DiagItemsList_List_Item15_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item15_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item15_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item15_Visible(bool digital)
        {
            DiagItemsList_List_Item15_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item16_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item16_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item16_Enable(bool digital)
        {
            DiagItemsList_List_Item16_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item16_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item16_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item16_Visible(bool digital)
        {
            DiagItemsList_List_Item16_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item17_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item17_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item17_Enable(bool digital)
        {
            DiagItemsList_List_Item17_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item17_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item17_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item17_Visible(bool digital)
        {
            DiagItemsList_List_Item17_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item18_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item18_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item18_Enable(bool digital)
        {
            DiagItemsList_List_Item18_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item18_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item18_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item18_Visible(bool digital)
        {
            DiagItemsList_List_Item18_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item19_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item19_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item19_Enable(bool digital)
        {
            DiagItemsList_List_Item19_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item19_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item19_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item19_Visible(bool digital)
        {
            DiagItemsList_List_Item19_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item2_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item2_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item2_Enable(bool digital)
        {
            DiagItemsList_List_Item2_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item2_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item2_Visible(bool digital)
        {
            DiagItemsList_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item20_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item20_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item20_Enable(bool digital)
        {
            DiagItemsList_List_Item20_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item20_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item20_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item20_Visible(bool digital)
        {
            DiagItemsList_List_Item20_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item21_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item21_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item21_Enable(bool digital)
        {
            DiagItemsList_List_Item21_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item21_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item21_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item21_Visible(bool digital)
        {
            DiagItemsList_List_Item21_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item22_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item22_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item22_Enable(bool digital)
        {
            DiagItemsList_List_Item22_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item22_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item22_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item22_Visible(bool digital)
        {
            DiagItemsList_List_Item22_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item23_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item23_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item23_Enable(bool digital)
        {
            DiagItemsList_List_Item23_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item23_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item23_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item23_Visible(bool digital)
        {
            DiagItemsList_List_Item23_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item24_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item24_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item24_Enable(bool digital)
        {
            DiagItemsList_List_Item24_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item24_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item24_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item24_Visible(bool digital)
        {
            DiagItemsList_List_Item24_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item3_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item3_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item3_Enable(bool digital)
        {
            DiagItemsList_List_Item3_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item3_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item3_Visible(bool digital)
        {
            DiagItemsList_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item4_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item4_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item4_Enable(bool digital)
        {
            DiagItemsList_List_Item4_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item4_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item4_Visible(bool digital)
        {
            DiagItemsList_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item5_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item5_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item5_Enable(bool digital)
        {
            DiagItemsList_List_Item5_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item5_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item5_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item5_Visible(bool digital)
        {
            DiagItemsList_List_Item5_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item6_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item6_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item6_Enable(bool digital)
        {
            DiagItemsList_List_Item6_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item6_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item6_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item6_Visible(bool digital)
        {
            DiagItemsList_List_Item6_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item7_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item7_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item7_Enable(bool digital)
        {
            DiagItemsList_List_Item7_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item7_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item7_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item7_Visible(bool digital)
        {
            DiagItemsList_List_Item7_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item8_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item8_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item8_Enable(bool digital)
        {
            DiagItemsList_List_Item8_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item8_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item8_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item8_Visible(bool digital)
        {
            DiagItemsList_List_Item8_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item9_Enable(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item9_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item9_Enable(bool digital)
        {
            DiagItemsList_List_Item9_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagItemsList_List_Item9_Visible(DiagItemsListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagItemsList_List_Item9_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_List_Item9_Visible(bool digital)
        {
            DiagItemsList_List_Item9_Visible((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void DiagItemsList_Set_Number_Of_Items(DiagItemsListUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.DiagItemsList_Set_Number_Of_ItemsState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagItemsList_Set_Number_Of_Items(ushort analog)
        {
            DiagItemsList_Set_Number_Of_Items((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void DiagItemsList_Set_Number_Of_Items(short analog)
        {
            DiagItemsList_Set_Number_Of_Items((sig, component) => sig.ShortValue = analog);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[4]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_4_ Items_4_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[5]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_5_ Items_5_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[6]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_6_ Items_6_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[7]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_7_ Items_7_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[8]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_8_ Items_8_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[9]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_9_ Items_9_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[10]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_10_ Items_10_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[11]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_11_ Items_11_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[12]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_12_ Items_12_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[13]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_13_ Items_13_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[14]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_14_ Items_14_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[15]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_15_ Items_15_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[16]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_16_ Items_16_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[17]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_17_ Items_17_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[18]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_18_ Items_18_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[19]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_19_ Items_19_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[20]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_20_ Items_20_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[21]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_21_ Items_21_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[22]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_22_ Items_22_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[23]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItems_23_ Items_23_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[{0}]
        /// </summary>
        public STEM107.Diagnostics.DiagItemsList.IItem Item { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "DiagItemsList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
