//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     STEM-107
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using STEM107;

namespace STEM107.Diagnostics.DiagItemsList
{

    /// <summary>
    /// Items[4]
    /// </summary>
    public partial interface IItems_4_ 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Diagnostics.DiagItemsList.Items[4].Diag-Online.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DiagOnline_PressEvent;

        /// <summary>
        /// Event Diagnostics.DiagItemsList.Items[4].Diag-Sync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DiagSync_PressEvent;

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Sync.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagSync_Visibility_fb(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Sync.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagSync_Visibility_fb(bool digital);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Online.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagOnline_Selected(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Online.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagOnline_Selected(bool digital);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Sync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DiagSync_Selected(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Sync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DiagSync_Selected(bool digital);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-IP-ID.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void DiagIPID_Indirect(Items_4_StringInputSigDelegate callback);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-IP-ID.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void DiagIPID_Indirect(string serial);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void DiagName_Indirect(Items_4_StringInputSigDelegate callback);

        /// <summary>
        /// Diagnostics.DiagItemsList.Items[4].Diag-Name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void DiagName_Indirect(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="items_4_">The <see cref="IItems_4_"/> on which to apply the feedback.</param>
    public delegate void Items_4_BoolInputSigDelegate(BoolInputSig boolInputSig, IItems_4_ items_4_);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="items_4_">The <see cref="IItems_4_"/> on which to apply the feedback.</param>
    public delegate void Items_4_StringInputSigDelegate(StringInputSig stringInputSig, IItems_4_ items_4_);

    /// <summary>
    /// Items[4]
    /// </summary>
    internal partial class Items_4_ : IItems_4_, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Diagnostics.DiagItemsList.Items[4].DiagItemCONTRACT.DiagOnline.Press
                /// Diagnostics.DiagItemsList.Items[4].Diag-Online.Press
                /// </summary>
                public const uint DiagOnline_PressEvent = 601;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Diagnostics.DiagItemsList.Items[4].DiagItemCONTRACT.DiagSync.Press
                /// Diagnostics.DiagItemsList.Items[4].Diag-Sync.Press
                /// </summary>
                public const uint DiagSync_PressEvent = 602;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.Items[4].DiagItemCONTRACT.DiagSync.Visibility_fb
                /// Diagnostics.DiagItemsList.Items[4].Diag-Sync.Visibility
                /// </summary>
                public const uint DiagSync_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.Items[4].DiagItemCONTRACT.DiagOnline.Selected
                /// Diagnostics.DiagItemsList.Items[4].Diag-Online.Selected
                /// </summary>
                public const uint DiagOnline_SelectedState = 602;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Diagnostics.DiagItemsList.Items[4].DiagItemCONTRACT.DiagSync.Selected
                /// Diagnostics.DiagItemsList.Items[4].Diag-Sync.Selected
                /// </summary>
                public const uint DiagSync_SelectedState = 603;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: Diagnostics.DiagItemsList.Items[4].DiagItemCONTRACT.DiagIPID.Indirect
                /// Diagnostics.DiagItemsList.Items[4].Diag-IP-ID.Indirect
                /// </summary>
                public const uint DiagIPID_IndirectState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: Diagnostics.DiagItemsList.Items[4].DiagItemCONTRACT.DiagName.Indirect
                /// Diagnostics.DiagItemsList.Items[4].Diag-Name.Indirect
                /// </summary>
                public const uint DiagName_IndirectState = 2;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_4_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Items_4_(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_4_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Items_4_(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_4_"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DiagOnline_PressEvent, onDiagOnline_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DiagSync_PressEvent, onDiagSync_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DiagOnline_PressEvent;
        private void onDiagOnline_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DiagOnline_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DiagSync_PressEvent;
        private void onDiagSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DiagSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void DiagOnline_Selected(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagOnline_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagOnline_Selected(bool digital)
        {
            DiagOnline_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagSync_Selected(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagSync_Selected(bool digital)
        {
            DiagSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DiagSync_Visibility_fb(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DiagSync_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagSync_Visibility_fb(bool digital)
        {
            DiagSync_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void DiagIPID_Indirect(Items_4_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.DiagIPID_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagIPID_Indirect(string serial)
        {
            DiagIPID_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void DiagName_Indirect(Items_4_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.DiagName_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void DiagName_Indirect(string serial)
        {
            DiagName_Indirect((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Items_4_", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            DiagOnline_PressEvent = null;
            DiagSync_PressEvent = null;
        }

        #endregion
    }
}
